server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: plan
          uri: http://localhost:8082
          predicates:
            - Path=/plans/**, 
        - id: member
          uri: http://localhost:8083
          predicates:
            - Path=/members/**, 
        - id: notification
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**, 
        - id: follow
          uri: http://localhost:8085
          predicates:
            - Path=/follows/**, 
        - id: recommendation
          uri: http://localhost:8086
          predicates:
            - Path=/recommendations/**, 
        - id: like
          uri: http://localhost:8087
          predicates:
            - Path=/likes/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: plan
          uri: http://plan:8080
          predicates:
            - Path=/plans/**, 
        - id: member
          uri: http://member:8080
          predicates:
            - Path=/members/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**, 
        - id: follow
          uri: http://follow:8080
          predicates:
            - Path=/follows/**, 
        - id: recommendation
          uri: http://recommendation:8080
          predicates:
            - Path=/recommendations/**, 
        - id: like
          uri: http://like:8080
          predicates:
            - Path=/likes/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
