apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow
  labels:
    app: follow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follow
  template:
    metadata:
      labels:
        app: follow
    spec:
      containers:
        - name: follow
          image: "username/follow:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
